database:
    uri: "postgresql+psycopg2://ekklesia_portal_db_user:ekklesia_portal_db_password@127.0.0.1/ekklesia_portal_db_name"
    fts_language: 'german'
app:
    instance_name: my_ekklesia_portal
    insecure_development_mode: false
    force_ssl: true
    tos_url: /pages/tos
    imprint_url: /pages/imprint
    data_protection_url: /pages/data_protection
    faq_url: /pages/faq
share:
    use_url_shortener: false
    hashtag: "PIRATEN"
    promote_account: "piratenpartei"
browser_session:
    secret_key: devkey
    cookie_secure: false
    permanent_lifetime: 999999
importer:
    testdiscourse:
        schema: discourse_post
        base_url: http://testdiscourse-local
exporter:
    testdiscourse:
        api_key: bd72000000000050000000000910000000000df088bd00000000002d9242dd06
        api_username: testuser
        category: 12
        base_url: https://testdiscourse-local

